name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"   # Only run when backend code changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      # 3. Go to backend folder and restore dependencies
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend

      # 4. Build the backend
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./backend

      # 5. Publish project (creates a package for deployment)
      - name: Publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./backend

      # 7. Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "backend20250920090759"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./backend/publish
